services:
  h2db:
    image: oscarfonts/h2
    container_name: h2_database
    restart: always
    ports:
      - "1521:1521"
      - "81:81"
    environment:
      H2_OPTIONS: "-ifNotExists"
    volumes:
      - h2_data:/opt/h2-data
    networks:
      - backend-api-network

networks:
  backend-api-network:

volumes:
  h2_data:
